"""add uuid_1c fields

Revision ID: 9c5ee2178209
Revises: c97e67c8e919
Create Date: 2024-09-18 19:20:04.410986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c5ee2178209"
down_revision: Union[str, None] = "c97e67c8e919"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brands", sa.Column("uuid_1c", sa.String(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_brands_uuid_1c"), "brands", ["uuid_1c"]
    )
    op.add_column("groups", sa.Column("uuid_1c", sa.String(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_groups_uuid_1c"), "groups", ["uuid_1c"]
    )
    op.add_column(
        "product_variations", sa.Column("name", sa.String(), nullable=True)
    )
    op.add_column(
        "product_variations", sa.Column("uuid_1c", sa.String(), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_product_variations_uuid_1c"),
        "product_variations",
        ["uuid_1c"],
    )
    op.add_column(
        "products", sa.Column("uuid_1c", sa.String(), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_products_uuid_1c"), "products", ["uuid_1c"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_products_uuid_1c"), "products", type_="unique")
    op.drop_column("products", "uuid_1c")
    op.drop_constraint(
        op.f("uq_product_variations_uuid_1c"),
        "product_variations",
        type_="unique",
    )
    op.drop_column("product_variations", "uuid_1c")
    op.drop_column("product_variations", "name")
    op.drop_constraint(op.f("uq_groups_uuid_1c"), "groups", type_="unique")
    op.drop_column("groups", "uuid_1c")
    op.drop_constraint(op.f("uq_brands_uuid_1c"), "brands", type_="unique")
    op.drop_column("brands", "uuid_1c")
    # ### end Alembic commands ###
