"""add sale_quantity field to product model and uuid_1c field to product variation property model

Revision ID: 06d063ddcc8e
Revises: 3edcd8aaea5e
Create Date: 2024-10-09 16:39:26.665543

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06d063ddcc8e"
down_revision: Union[str, None] = "3edcd8aaea5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_properties", sa.Column("uuid_1c", sa.String(), nullable=False)
    )
    op.create_unique_constraint(
        op.f("uq_product_properties_uuid_1c"),
        "product_properties",
        ["uuid_1c"],
    )
    op.add_column(
        "product_variations",
        sa.Column("sale_quantity", sa.Integer(), nullable=False),
    )
    op.alter_column(
        "products", "brand_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products", "brand_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("product_variations", "sale_quantity")
    op.drop_constraint(
        op.f("uq_product_properties_uuid_1c"),
        "product_properties",
        type_="unique",
    )
    op.drop_column("product_properties", "uuid_1c")
    # ### end Alembic commands ###
