"""remove unique from group name field

Revision ID: 223ef7e750eb
Revises: e0c6dac32d9a
Create Date: 2024-10-08 23:50:12.490688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "223ef7e750eb"
down_revision: Union[str, None] = "e0c6dac32d9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_groups_name", "groups", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_groups_name", "groups", ["name"])
    # ### end Alembic commands ###
