"""change Brand image filed name

Revision ID: 3aa3fce2a003
Revises: 3a6ed6ac5e77
Create Date: 2024-10-11 06:05:53.639109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3aa3fce2a003"
down_revision: Union[str, None] = "3a6ed6ac5e77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("brands", "image_url", new_column_name="image")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("brands", "image", new_column_name="image_url")
    # ### end Alembic commands ###
