"""add created and updated fields to product table

Revision ID: adbfdaabf588
Revises: 16ca61352891
Create Date: 2024-08-06 19:16:58.091099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adbfdaabf588"
down_revision: Union[str, None] = "16ca61352891"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "products", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "updated_at")
    op.drop_column("products", "created_at")
    # ### end Alembic commands ###
