"""add active field to product and product_variation models

Revision ID: 8a52d9ec7fa0
Revises: 6f0e77b1308b
Create Date: 2024-10-17 01:39:23.858146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a52d9ec7fa0"
down_revision: Union[str, None] = "6f0e77b1308b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("uds_transaction_id", sa.String(), nullable=True)
    ),
    op.add_column(
        "product_variations",
        sa.Column("active", sa.Boolean(), nullable=False, default=True),
    )
    op.add_column(
        "products",
        sa.Column("active", sa.Boolean(), nullable=False, default=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "active")
    op.drop_column("product_variations", "active")
    op.drop_column("orders", "uds_transaction_id")
    # ### end Alembic commands ###
