"""add payment_data field to order model

Revision ID: 2b809996e00a
Revises: 8a52d9ec7fa0
Create Date: 2024-11-01 04:13:32.077012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b809996e00a"
down_revision: Union[str, None] = "8a52d9ec7fa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("payment_data", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "payment_data")
    # ### end Alembic commands ###
