"""add additional fields for user table

Revision ID: efd81cd6c2fe
Revises: 1c8ec6e08c44
Create Date: 2024-07-25 17:37:23.535367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efd81cd6c2fe"
down_revision: Union[str, None] = "1c8ec6e08c44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("nickname", sa.String(), nullable=False))
    op.add_column(
        "users", sa.Column("phone_number", sa.String(), nullable=False)
    )
    op.create_unique_constraint(
        op.f("uq_users_nickname"), "users", ["nickname"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_nickname"), "users", type_="unique")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "nickname")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
