"""add discount, final_price, created-at and updated_at fields to order table

Revision ID: 6f0e77b1308b
Revises: 3aa3fce2a003
Create Date: 2024-10-16 19:31:14.106166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f0e77b1308b"
down_revision: Union[str, None] = "3aa3fce2a003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("delivery", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("discount", sa.Integer(), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("final_price", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "final_price")
    op.drop_column("orders", "updated_at")
    op.drop_column("orders", "created_at")
    op.drop_column("orders", "discount")
    op.drop_column("orders", "delivery")
    # ### end Alembic commands ###
