"""set unique name field for brand table

Revision ID: 16ca61352891
Revises: 8d591855268b
Create Date: 2024-07-28 18:41:20.550367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16ca61352891"
down_revision: Union[str, None] = "8d591855268b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_brands_name"), "brands", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_brands_name"), "brands", type_="unique")
    # ### end Alembic commands ###
