"""change Brand image filed type to FileType

Revision ID: 3a6ed6ac5e77
Revises: e028950bacb8
Create Date: 2024-10-11 04:15:00.205859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a6ed6ac5e77"
down_revision: Union[str, None] = "e028950bacb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "brands", "image_url", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "brands", "image_url", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
