"""nullable=false uuid_1c fields

Revision ID: 312ab4303c6e
Revises: 9c5ee2178209
Create Date: 2024-09-18 19:23:05.636654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "312ab4303c6e"
down_revision: Union[str, None] = "9c5ee2178209"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "brands", "uuid_1c", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "groups", "uuid_1c", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "product_variations",
        "name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "product_variations",
        "uuid_1c",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "products", "uuid_1c", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products", "uuid_1c", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "product_variations",
        "uuid_1c",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "product_variations", "name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "groups", "uuid_1c", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "brands", "uuid_1c", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
