"""add uix_image_product_url constraint to ProductImage model

Revision ID: e028950bacb8
Revises: ad25f0fd5308
Create Date: 2024-10-09 17:22:39.551530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e028950bacb8"
down_revision: Union[str, None] = "ad25f0fd5308"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_image_product_url", "product_images", ["product_id", "url"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uix_image_product_url", "product_images", type_="unique"
    )
    # ### end Alembic commands ###
