"""add parent product to CartProduct model

Revision ID: affce0bf55c8
Revises: 845e9f743dbd
Create Date: 2025-06-20 19:22:12.351464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "affce0bf55c8"
down_revision: Union[str, None] = "845e9f743dbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_products",
        sa.Column("parent_product_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_cart_products_parent_product_id_cart_products"),
        "cart_products",
        "cart_products",
        ["parent_product_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_cart_products_parent_product_id_cart_products"),
        "cart_products",
        type_="foreignkey",
    )
    op.drop_column("cart_products", "parent_product_id")

    # ### end Alembic commands ###
