"""add unique constraint to category property value model

Revision ID: 207ec24e467c
Revises: 0e1fc18ab310
Create Date: 2025-01-08 19:20:20.520829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "207ec24e467c"
down_revision: Union[str, None] = "0e1fc18ab310"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_category_property_value",
        "values",
        ["category_property_id", "value"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_category_property_value", "values", type_="unique")
    # ### end Alembic commands ###
