"""Добавлены name_ky и name_en в Category Prooperty

Revision ID: 2f86012cf815
Revises: 4f33c4c102df
Create Date: 2025-03-15 01:36:34.539785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f86012cf815"
down_revision: Union[str, None] = "4f33c4c102df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category_properties", sa.Column("name_ky", sa.String(), nullable=True)
    )
    op.add_column(
        "category_properties", sa.Column("name_en", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category_properties", "name_en")
    op.drop_column("category_properties", "name_ky")
    # ### end Alembic commands ###
