"""Добавлены name_ky и name_en в Category

Revision ID: 4f33c4c102df
Revises: 9ab6028988ff
Create Date: 2025-03-15 01:00:27.480122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f33c4c102df"
down_revision: Union[str, None] = "9ab6028988ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories", sa.Column("name_ky", sa.String(), nullable=True)
    )
    op.add_column(
        "categories", sa.Column("name_en", sa.String(), nullable=True)
    )
    op.add_column("groups", sa.Column("name_ky", sa.String(), nullable=True))
    op.add_column("groups", sa.Column("name_en", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "name_en")
    op.drop_column("groups", "name_ky")
    op.drop_column("categories", "name_en")
    op.drop_column("categories", "name_ky")
    # ### end Alembic commands ###
