"""Add banner

Revision ID: 19e48c24d39d
Revises: 6035de0e25cd
Create Date: 2025-05-06 20:11:18.758215

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19e48c24d39d"
down_revision: Union[str, None] = "6035de0e25cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("banners", sa.Column("title_ky", sa.Text(), nullable=True))
    op.add_column("banners", sa.Column("title_en", sa.Text(), nullable=True))
    op.add_column(
        "banners", sa.Column("description_ky", sa.Text(), nullable=True)
    )
    op.add_column(
        "banners", sa.Column("description_en", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("banners", "description_en")
    op.drop_column("banners", "description_ky")
    op.drop_column("banners", "title_en")
    op.drop_column("banners", "title_ky")
    # ### end Alembic commands ###
