"""add product variation image model

Revision ID: 2dd6710fa44e
Revises: a999c9fe7b01
Create Date: 2025-04-17 16:39:21.187131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2dd6710fa44e"
down_revision: Union[str, None] = "a999c9fe7b01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_variation_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("variation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["variation_id"],
            ["product_variations.id"],
            name=op.f(
                "fk_product_variation_images_variation_id_product_variations"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_product_variation_images")
        ),
        sa.UniqueConstraint(
            "variation_id", "url", name="uix_image_product_variation_url"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_variation_images")
    # ### end Alembic commands ###
