"""add payment_responses field to Order model

Revision ID: 845e9f743dbd
Revises: 19e48c24d39d
Create Date: 2025-05-12 17:01:28.105319

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "845e9f743dbd"
down_revision: Union[str, None] = "19e48c24d39d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("payment_responses", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "payment_responses")
    # ### end Alembic commands ###
