"""Sdek id added in Order

Revision ID: a698c2417cab
Revises: a999c9fe7b01
Create Date: 2025-04-17 04:52:49.737420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a698c2417cab"
down_revision: Union[str, None] = "a999c9fe7b01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("sdek_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "sdek_id")
    # ### end Alembic commands ###
