"""Добавлены поля для Address

Revision ID: a721647d9eb3
Revises: 27fa42177b38
Create Date: 2025-04-22 18:23:52.010405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a721647d9eb3"
down_revision: Union[str, None] = "27fa42177b38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresss", sa.Column("country_code", sa.String(), nullable=True)
    )
    op.add_column(
        "addresss", sa.Column("city_uuid", sa.String(), nullable=False)
    )
    op.add_column(
        "addresss", sa.Column("city_code", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("addresss", "city_code")
    op.drop_column("addresss", "city_uuid")
    op.drop_column("addresss", "country_code")
    # ### end Alembic commands ###
