"""Add banner

Revision ID: a93a84f81901
Revises: ec821f7bae8c
Create Date: 2025-05-06 18:18:18.755577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a93a84f81901"
down_revision: Union[str, None] = "ec821f7bae8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banners",
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_banners")),
    )
    op.create_table(
        "banner_products",
        sa.Column("banner_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["banner_id"],
            ["banners.id"],
            name=op.f("fk_banner_products_banner_id_banners"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_banner_products_product_id_products"),
        ),
        sa.PrimaryKeyConstraint(
            "banner_id", "product_id", name=op.f("pk_banner_products")
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:

    op.drop_table("banner_products")
    op.drop_table("banners")
    # ### end Alembic commands ###
