"""add is_main filed for product image model

Revision ID: 9ab6028988ff
Revises: 207ec24e467c
Create Date: 2025-03-04 03:32:02.726817

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ab6028988ff"
down_revision: Union[str, None] = "207ec24e467c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add the is_main column, allowing NULL values initially
    op.add_column(
        "product_images",
        sa.Column("is_main", sa.Boolean(), nullable=True)
    )

    # Step 2: Set a default value (e.g., FALSE) for existing rows
    op.execute("UPDATE product_images SET is_main = FALSE")

    # Step 3: Alter the column to enforce NOT NULL
    op.alter_column(
        "product_images",
        "is_main",
        nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_images", "is_main")
    # ### end Alembic commands ###
