"""Изменение полей

Revision ID: 170ccab24aa4
Revises: 08986349139a
Create Date: 2025-05-01 00:15:38.658862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "170ccab24aa4"
down_revision: Union[str, None] = "08986349139a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "addresss", "country_code", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "addresss", "address", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "addresss", "address", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "addresss", "country_code", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
