"""Изменение полей

Revision ID: ec821f7bae8c
Revises: a721647d9eb3
Create Date: 2025-05-01 01:22:34.773175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec821f7bae8c"
down_revision: Union[str, None] = "a721647d9eb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "orders", sa.Column("country_code", sa.String(), nullable=True)
    )
    op.add_column("orders", sa.Column("city_code", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("city_uuid", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "city_uuid")
    op.drop_column("orders", "city_code")
    op.drop_column("orders", "country_code")
    op.alter_column(
        "addresss", "address", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "addresss", "city_code", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "addresss", "city_uuid", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
