"""Добавлены name_ky и name_en в Category Prooperty

Revision ID: c5dd116e98be
Revises: 2f86012cf815
Create Date: 2025-03-16 21:30:40.219615

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5dd116e98be"
down_revision: Union[str, None] = "2f86012cf815"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("title_ky", sa.String(), nullable=True)
    )
    op.add_column(
        "products", sa.Column("title_en", sa.String(), nullable=True)
    )
    op.add_column(
        "products", sa.Column("description_en", sa.Text(), nullable=True)
    )
    op.add_column(
        "products", sa.Column("description_ky", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "description_ky")
    op.drop_column("products", "description_en")
    op.drop_column("products", "title_en")
    op.drop_column("products", "title_ky")
    # ### end Alembic commands ###
