"""Add banner

Revision ID: e5e2f5c6bab0
Revises: a93a84f81901
Create Date: 2025-05-06 19:11:07.092262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5e2f5c6bab0"
down_revision: Union[str, None] = "a93a84f81901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "banners", sa.Column("product_ids", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("banners", "product_ids")
    # ### end Alembic commands ###
